apiVersion: ENC[AES256_GCM,data:EW0=,iv:7BN8d/7r/M/jXDC5aIctXvbWuw8kMytbhmDZ5x+JO5k=,tag:mXwR0SBrRUjwRzhLhuAMoA==,type:str]
kind: ENC[AES256_GCM,data:F88CYkqr,iv:rlr922Evu75LiC8FGc22hNIKcdOtpI9Rh93mYNzrIwE=,tag:lwnrQYUz+Uo+zW0NneR12A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:MqcHN7tj0ZzoWic9fGqiEzR1AuH4M1gV1DVS9jdo6ihF,iv:1i8VXr6GdpKi8/wJiwOOe2fHQ3Qsxff47cDkCCxHEc0=,tag:PjJjFb0TnEThw2SN99xBvQ==,type:str]
    namespace: ENC[AES256_GCM,data:A40N9iS/PQI9NQ==,iv:IIbimficydKN2XrgZFDJlaV8t6agtOEhc6D7sv4sTLw=,tag:7wzeI1ioYjJ4U9zE5JsPpA==,type:str]
type: ENC[AES256_GCM,data:1tXyZ/JX,iv:HxyIWTz7H/9IBTiYENOF6ME/szt3M3BtL3DXyNHR7JI=,tag:ZDoQPBbB0pEKCeiy13Vy7Q==,type:str]
stringData:
    replace_with_required_key: ENC[AES256_GCM,data:LrvG9sXjoBCXxWy2cEZByGa9GeLdDXQ=,iv:kT/r4UiVd3Vz+rk2TjJq9kDR+BeuCoxr3/gZ27FfoNQ=,tag:/PVtZa68ZilUdAlq9g3eDQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rwwjrh53mxx43xps8glry9uk4aga839wlr85ceftvr0905dgqvxsrgke24
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUZWhkSjVhZ2UxblowbUov
            dktRT0VlSjZLMzJObnVCYnVUbWxJM1EvbmpzClFGNTJtUGJvT2t1SnBRZFY0WG14
            VURzTUt6L3dSSVZJcVNDeFlzNnZyY0kKLS0tIFFGM1I1ODBLOTRoM09wTXh6bGxC
            cUNveklCY3JsYmtZekJ6VlMzOVNmQnMKcoBxfrlmZcuVXrAWcX9PX+r5I/mLH1g3
            XvqgooEsvcNIY5fWrkKLsuEJL+red07WFC2LkU+bCCIXYDcrJ9j1ug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-26T21:36:48Z"
    mac: ENC[AES256_GCM,data:tQ00P9fSjafDXE7pf1SxClOoYuHI4A53cxr6XWAzObB21xOjvezxNQ2BFyb09KR+9h1ET7QrDKmGd29aNy0ZJ5kfTXcc1uU4XbBfhCW4Up4WeEey4ugp7fZtcBOqVQv5tj8sqA/zAG05ny2D8aKvvFX5MS3CPVX1TBt8j6pW0a0=,iv:iHiSzNVabMY1Xcs7glbsmi9ub8hJ50N88j/9xD9+B1Y=,tag:pwnRGh0GK91dOn26uwKNfA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4